### ISSUE TITLE
Allow to pick commits from GitHub projects

### ISSUE THREAD

**Issue by schneigu** [jazz-community/rtc-git-commit-picker#7]
RTC V.6.0.5 will have the possibility to define the GIT type of a repository.

The GIT Commit Picker should support public projects hosted on GitHub (e.g. from our own community site)

If behind a Firewall the GIT picker is the only possible way to interact with a public infrastructure without opening a backdoor or having a business partner link.

**Comment by innerjoin** [comment]
@jazz-community/git-integration-team 
The current implementation creates a _back link_ from GitLab to RTC. 
Shall this also be the case for public GitHub projects linking to a protected, internal RTC Server?

**Comment by SBI-** [comment]
I think it would be nice to be able to configure the behaviour on a repository basis. You can also have private GitHub repositories, where you might prefer to have internal links. Also, if you have a public jazz instance, you might also want to have the links available.

**Comment by innerjoin** [comment]
That is true indeed, do you see a possibility to store that decision on a repository level?

**Comment by schneigu** [comment]
I would just do it like today. Why should it be configurable? Just for a better end user experiance?

When someone clicks the link an he has no permission to access it, it will simply not work. So If it is public you will see the link and are able to copy & paste it.

**Comment by innerjoin** [comment]
@schneigu I have updated your comment above to make it more clear to me...

@schneigu thank you for your arguments, you have convinced me, but we should line out this decision in the 'README' once we are implementing GitHub support

**Comment by innerjoin** [comment]
This project has been phased out a while ago. Anyone interested in integrating RTC with GitLab or GitHub should check out the [RTC Git Connector](https://github.com/jazz-community/rtc-git-connector) project, which covers all the use cases of this repo plus many more.
If you feel like this issue is still relevant with what the [RTC Git Connector](https://github.com/jazz-community/rtc-git-connector) aims to provide, feel free to open a new issue there
