### ISSUE TITLE
Provid a GIT Commit Links list presentation for Work Item Editor

### ISSUE THREAD

**Issue by schneigu** [jazz-community/rtc-git-commit-picker#8]
Rich hover is nice to have, but sometime it eould be good to see the informations inside the link value in a list.

Provide a presentation which showes the GIT Commits in a simple tabular list. The presentation should be possible to add to the workitem editor in a section container.

This should be bundled into the package
as "GIT Integration Feature Pack"

**Comment by innerjoin** [comment]
This project has been phased out a while ago. Anyone interested in integrating RTC with GitLab or GitHub should check out the [RTC Git Connector](https://github.com/jazz-community/rtc-git-connector) project, which covers all the use cases of this repo plus many more.
If you feel like this issue is still relevant with what the [RTC Git Connector](https://github.com/jazz-community/rtc-git-connector) aims to provide, feel free to open a new issue there
