### ISSUE TITLE
Provide a Workitem Query Dashboard Widget showing GIT Commit links

### ISSUE THREAD

**Issue by schneigu** [jazz-community/rtc-git-commit-picker#9]
Complementary to existing Workitem Query Dashboard Widgets we should have a GIT Commit Work Item Query widget.

It should be possible to select an existing query and the result shows you the Work Item Summary and number of GIT Commits in brackets.
The individul Work Item should be expandable if there exists a GIT Commit link. 
When expanded the GIT Commits should be shown in a tabular list with the informations out of the link value
The liat should be active with rich hover as well as clickon links to open the commits in GIT web UI.

**Comment by innerjoin** [comment]
If implemented, this should happen in another repository as it is independent from the Git Commit Picker

Nevertheless, we should keep this open as long as there is no work started on this in a new repo

**Comment by innerjoin** [comment]
This project has been phased out a while ago. Anyone interested in integrating RTC with GitLab or GitHub should check out the [RTC Git Connector](https://github.com/jazz-community/rtc-git-connector) project, which covers all the use cases of this repo plus many more.
If you feel like this issue is still relevant with what the [RTC Git Connector](https://github.com/jazz-community/rtc-git-connector) aims to provide, feel free to open a new issue there
